export const GET_PROFILE_IMG = 'http://localhost:8080/api/v1/user/image/';
export const GET_RECIPE_IMG = 'http://localhost:8080/api/v1/recipe/image/';
export const POST_PROFILE_IMG = 'http://localhost:8080/api/v1/user/image';
export const POST_RECIPE_IMG = 'http://localhost:8080/api/v1/recipe/image';
export const POST_NEW_USER = 'http://localhost:8081/api/v1/auth';
export const POST_LOG_IN = 'http://localhost:8081/api/v1/auth/login';
export const GET_USER = 'http://localhost:8081/api/v1/user/';
export const PATCH_USER = 'http://localhost:8081/api/v1/user/';
export const POST_NEW_RECIPE ='http://localhost:8082/api/v1/recipe/create'